# Generated by Django 4.1.3 on 2023-01-02 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Codes',
            fields=[
                ('code_id', models.IntegerField(primary_key=True, serialize=False)),
                ('points', models.IntegerField(default=0)),
                ('title', models.TextField(default='')),
                ('info', models.TextField(blank=True, default='', null=True)),
                ('short_code', models.CharField(blank=True, default='', max_length=3, null=True, unique=True)),
            ],
        ),
    ]
