# Generated by Django 4.1.3 on 2023-01-02 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codes',
            name='title',
            field=models.CharField(default='', max_length=20),
        ),
    ]
