# Generated by Django 4.1.3 on 2023-01-02 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_codes_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codes',
            name='short_code',
            field=models.CharField(blank=True, default='', max_length=4, null=True, unique=True),
        ),
    ]
