# Generated by Django 4.1.3 on 2023-01-09 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_alter_codes_title_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
