# Generated by Django 4.1.3 on 2023-01-10 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_attendance_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codes',
            name='short_code',
        ),
    ]
